version: '3.7'

services:
  adminer-db:
    image: adminer
    ports:
      - 8089:8080
  mysql-db:
    image: mysql:lastest
    environment:
      MYSQL_ROOT_PASSWORD: nokianokia134
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: nokianokia134
  backup-db:
    image: databack/mysql-backup
    user: "0"
    volumes:
      - < Spécifier le chemin d'accès absolu >/db:/db
    environment:
      - DB_DUMP_TARGET=/db
      - DB_USER=root
      - DB_PASS=nokianokia134
      - DB_NAMES=database test
      - DB_DUMP_BY_SCHEMA=true
      - DB_DUMP_CRON=* * * * *
      - DB_SERVER=mysql-db
      - DB_PORT=3306
